#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#00897b'
TEXT='#0EB8B9E6'
WRONG='#880000'
VERIFYING='#00564d'

i3lock \
--insidever-color=$CLEAR     \
--color=$DEFAULT               \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--greeter-color=$TEXT        \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$TEXT          \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 10                    \
--clock                      \
--indicator                  \
# --greeter-text="Welcome Back!" \
--verif-text="..." \
--wrong-text="..." \
# --time-str="%H %M %S"        \
# --date-str="%A, %Y-%m-%d"       \
# --keylayout 1                \
