colors:

  bright:
    black: '#585B70'
    blue: '#89B4FA'
    cyan: '#94E2D5'
    green: '#A6E3A1'
    magenta: '#F5C2E7'
    red: '#F38BA8'
    white: '#A6ADC8'
    yellow: '#F9E2AF'

  cursor:
    cursor: '#F5E0DC'
    text: '#1E1E2E'

  dim:
    black: '#45475A'
    blue: '#89B4FA'
    cyan: '#94E2D5'
    green: '#A6E3A1'
    magenta: '#F5C2E7'
    red: '#F38BA8'
    white: '#BAC2DE'
    yellow: '#F9E2AF'

  hints:
    end:
      background: '#A6ADC8'
      foreground: '#1E1E2E'
    start:
      background: '#F9E2AF'
      foreground: '#1E1E2E'

  indexed_colors:
    - color: '#FAB387'
      index: 16
    - color: '#F5E0DC'
      index: 17

  normal:
    black: '#45475A'
    blue: '#89B4FA'
    cyan: '#94E2D5'
    green: '#A6E3A1'
    magenta: '#F5C2E7'
    red: '#F38BA8'
    white: '#BAC2DE'
    yellow: '#F9E2AF'

  primary:
    background: '#1E1E2E'
    bright_foreground: '#CDD6F4'
    dim_foreground: '#CDD6F4'
    foreground: '#CDD6F4'

  search:
    focused_match:
      background: '#A6E3A1'
      foreground: '#1E1E2E'
    footer_bar:
      background: '#A6ADC8'
      foreground: '#1E1E2E'
    matches:
      background: '#A6ADC8'
      foreground: '#1E1E2E'

  selection:
    background: '#F5E0DC'
    text: '#1E1E2E'

  vi_mode_cursor:
    cursor: '#B4BEFE'
    text: '#1E1E2E'

cursor:
  style: Beam
  vi_mode_style: Beam

env:
  TERM: xterm-256color

font:
  bold:
    family: JetBrainsMonoNL Nerd Font Mono
    style: Bold
  glyph_offset:
    y: 0
  italic:
    family: JetBrainsMonoNL Nerd Font Mono
    style: Italic
  normal:
    family: JetBrainsMonoNL Nerd Font Mono
    style: Regular
  offset:
    y: 0
  size: 10

scrolling:
  history: 1000
  multiplier: 3

shell:
  program: /bin/zsh

theme: Soothing

window:
  decorations: none
  dimensions:
    columns: 80
    lines: 24
  opacity: 0.8
  padding:
    x: 12
    y: 12
