:set autoindent
:set number
:set relativenumber
:set tabstop=2
:set shiftwidth=2
:set expandtab
:set mouse=a
:set clipboard+=unnamedplus
:set pumheight=10
:set noshowmode
:set splitbelow
:set splitright
